### ISSUE TITLE
What about misandry identification?

### ISSUE THREAD

**Issue by impredicative** [punyajoy/AMI-EVALITA2018#1]
Can't you have a generic model for both misogyny and misandry? Why be sexist?

**Comment by binny-mathew** [comment]
Hi,
As the [AMI task](https://amievalita2018.wordpress.com) was for misogyny identification, we are not able to look into Misandry. We acknowledge that `Misandry Classification' is an important task, but as we do not have the data for the task, we were not able to build models for the same. As suggested by you, a generic model that could identify both misogyny and misandry will be an invaluable contribution to the research.
